### ISSUE TITLE
Got error in line 6

### ISSUE THREAD

**Issue by dark3510** [dmatviichuk/Telegram-SMS-Bomber#3]
I have got an error in line 6 please tell me how to fix
If anyone knows

https://user-images.githubusercontent.com/84274107/140420719-8ec54b7f-a83f-497b-96bb-097874a3f378.mp4

**Comment by dmatviichuk** [comment]
Try to install bot api: _pip install pyTelegramBotAPI phonenumbers requests_

**Comment by dark3510** [comment]
I have already installed it 
And it gives me positive response

**Comment by dark3510** [comment]
Mean it gives me error

**Comment by dark3510** [comment]
Means it give me same error
