### ISSUE TITLE
Python bot.py not working

### ISSUE THREAD

**Issue by dark3510** [dmatviichuk/Telegram-SMS-Bomber#4]
How to use Bot.py
I use python3 Bot.py 
But where I enter the victim id or number

https://user-images.githubusercontent.com/84274107/140569759-f6093167-82d0-47aa-9f66-cc4598b1b919.mp4

I don't get any next page or any option
Please help me

**Comment by dmatviichuk** [comment]
You should not edit Bot.py. Firstly, create new bot in Telegram via Bot Father, get an api key, than change it in the third line in Bot.py. Launch it(python3 Bot.py), open your Telegram Bot and type /start. Thats all.

**Comment by dark3510** [comment]
I have already changed the token

**Comment by dark3510** [comment]
But it cannot redirect to next 
Where we use /start in terminal or telegram

**Comment by dark3510** [comment]
Now I find all things but it cannot sent the any  message to victim

**Comment by dark3510** [comment]
Bro number dene ke baad bhi nahi ho rha hai 
Yee tool termux mei use kar rha hoo chala ga na
